#!/bin/bash

cp -r 0_orig 0
blockMesh 2>&1 | tee -a log.blockMesh
checkMesh 2>&1 | tee -a log.checkMesh
decomposePar -cellDist 2>&1 | tee -a log.decomposePar
mpirun -np 10 potentialFoam -writep -parallel 2>&1 | tee -a log.potentialFoam
mpirun -np 10 simpleFoam -parallel 2>&1 | tee -a log.simpleFoam
reconstructPar -latestTime 2>&1 | tee -a log.reconstructPar

#------------------------------------------------------------------------------
